branch-defaults:
  portfolio:
    environment: portfolio-app-production
    group_suffix: null
global:
  application_name: app_portfolio
  branch: null
  default_ec2_keyname: aws-portfolio-app
  default_platform: Puma with Ruby 2.6 running on 64bit Amazon Linux
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
